apiVersion: v1
kind: Service
metadata:
  name: api-access-management-service
  namespace: dtag-dev
  labels:
    app: api-access-management-service
    version: latest
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
  - port: 18907
    nodePort: 32767
    targetPort: 9026
    protocol: TCP
  selector:
    app: api-access-management-service
    version: latest