apiVersion: 1.0.0
keycloakApiUserUrl: http://172.29.1.106:30955/keycloak/create
spring:
    data:
        mongodb:
            database: BMP_APIACCESS
            host: 172.29.1.114
            port: 27017
server:
    connection-timeout: 5000
    port: 9026
